version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-todo_db}
      - XAI_API_KEY=${XAI_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET:-default_secret_key_for_development}
    depends_on:
      - db
    restart: unless-stopped
    command: >
      bash -c "python -c 'from app import app, db; from models import User, Task, Category; app.app_context().push(); db.create_all()' && 
      flask run --host=0.0.0.0 --port=8080"

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-todo_db}
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 